### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by mrofcodyx** [DevVj-1/Face_Checker.io#1]
Traceback (most recent call last):
  File "/opt/tools/osint/photo/Face_Checker_io/Face_Checker_io/GUI.py", line 196, in <module>
    root.iconbitmap(r's.ico')
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "s.ico" not defined

![image](https://github.com/user-attachments/assets/8f794cc1-0082-47de-80cd-7192ba612a6a)

**Comment by DevVj-1** [comment]
Make sure all files are in one place :)
The ICO file format is an image file format for program icons 
![make-sure-all-files-in-one-place](https://github.com/user-attachments/assets/9c365d2f-c87f-4a37-9a71-bb7828afa5dc)
